### ISSUE TITLE
CCC "check all" behavior a bit confusing

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#330]
When I select the ADS check all button, I can see all other buttons change. This is expected UI. 

When I set the check all bonus to 0, all of the other numbers stay the same. This is confusing UI.

Another complication with this UI scheme is that the "check all" bonus defaults to zero, but there are non-zero entries in other boxes that are not overwritten. 

(This would also be a complication for the radio buttons if GDS were not the default for all property years.)

I think the right behavior is that check all bonus default should be x.yz or similar, and then if someone overwrites it with numbers, all of the other numbers are overwritten. Perhaps none of the check all radio buttons should be selected by default.

**Comment by PeterDSteinberg** [comment]
Fixed in #319

**Comment by jdebacker** [comment]
I still see this issue:
![ccc_checkall](https://cloud.githubusercontent.com/assets/10715924/18991527/1927706c-86e7-11e6-9dfb-8459256f4b9d.png)

Perhaps we should drop this - it's been difficult to get the UI to work correctly and the model doesn't handle these check all inputs at all right now.
cc @PeterDSteinberg

**Comment by jdebacker** [comment]
I believe this issue can be closed.  Can't find PR, but "check all" has been removed.

**Comment by talumbau** [comment]
closed via #347 which removed Check All.
